version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"  

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vote_db
    ports:
      - "5432:5432" 
    volumes:
      - ./fastapi/vote_db.sql:/docker-entrypoint-initdb.d/vote_db.sql

  worker:
    build:
      context: ./RedisToPostgres
    depends_on:
      - redis
      - db

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "5000:80"  
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis 
      - DB_HOST=db 

  result:
    build:
      context: ./result 
    ports:
      - "5001:5001"  
    depends_on:
      - db  
    environment:
      - DB_HOST=db  
